version: "3"
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard-jdownloader
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Mexico_City
    volumes:
      - /home/cupid/Docker/jdownloader/wireguard/config:/config
    ports:
      - 3129:3129
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  jdownloader:
    image: jaymoulin/jdownloader
    container_name: jdownloader-vpn
    user: 1000:100
    network_mode: "service:wireguard"
    depends_on:
      - wireguard
    volumes:
      - /home/cupid/Docker/jdownloader/appdata:/opt/JDownloader/cfg
      # - ./downloads:/opt/JDownloader/Downloads
      - /home/cupid/Docker/jdownloader/appdata/logs:/opt/JDownloader/logs
      - /home/MEDIA/Jdownloader:/opt/JDownloader/Downloads
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYJD_USER: $MYJD_USER
      MYJD_PASSWORD: $MYJD_PASSW
      MYJD_DEVICE_NAME: pixelmedia
      #XDG_DOWNLOAD_DIR: /opt/JDownloader/Downloads
    restart: unless-stopped
