version: "3.8"

services:
  duckdnsmc:
    image: linuxserver/duckdns
    container_name: duckdns
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "America/Mexico_City"
      SUBDOMAINS: "mimundo3d.duckdns.org"
      TOKEN: $TOKEN
    restart: unless-stopped
