---
services:
  duckdnsmc:
    image: linuxserver/duckdns
    container_name: duckdns
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "America/Mexico_City"
      SUBDOMAINS: $SUBDOMAIN
      TOKEN: $TOKEN
    restart: unless-stopped
