version: "3.8"

services:
  minecraft:
    image: itzg/minecraft-server:mod
    container_name: mcserver-geyser-fabric
    environment:
      TYPE: "FABRIC"
      FABRIC_LAUNCHER_VERSION: "0.11.2"
      FABRIC_LOADER_VERSION: "0.14.18"
      PACKWIZ_URL: "https://raw.githubusercontent.com/axolotl13/Dockerfiles/master/Minecraft-Server/Geyser-Fabric/Pack/Server/pack.toml"
      EULA: "TRUE"
      MEMORY: "2500M"
      VERSION: "1.19.4"
      TZ: "America/Mexico_City"
      # Minecraft Game Options
      GAMEMODE: "survival"
      MOTD: "\\u00A7f\\u2583\\u2584\\u2585\\u2586\\u00A76\\u00A7l\\u00A7o Private Personal\\u00A7r\\u00A7l \\u00A7c\\u00A7l\\u00A7mServer\\u00A7e\\u00A7l \\u2586\\u2585\\u2584\\u2583"
      DIFFICULTY: "hard"
      PVP: "true"
      MAX_PLAYERS: 20
      ONLINE_MODE: "true"
      VIEW_DISTANCE: 10
      SIMULATION_DISTANCE: 10
      SPAWN_PROTECTION: 16
      ICON: "https://raw.githubusercontent.com/axolotl13/Dockerfiles/master/Minecraft-Server/Icons/warden2.png"
    volumes:
      - /data:/data
    ports:
      - 25565:25565
      - 19132:19132/udp
    restart: unless-stopped
