version: "3.8"

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft-server-fabric
    environment:
      TYPE: "FABRIC"
      FABRIC_LAUNCHER_VERSION: "0.11.2"
      FABRIC_LOADER_VERSION: "0.14.18"
      EULA: "TRUE"
      MEMORY: "2500M"
      VERSION: "1.19.4"
      TZ: "America/Mexico_City"
    volumes:
      - /home/joker/.minecraft-server:/data
    ports:
      - 25565:25565
    restart: unless-stopped
