version: "2.1"
services:
  database:
    image: yobasystems/alpine-mariadb
    container_name: database
    restart: unless-stopped
    environment:
      MYSQL_USER: $MYSQL_USER
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSW
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_PASSWORD: $MYSQL_PASSW
      # MYSQL_ROOT_HOST: sqlberry
      # MARIADB_MYSQL_LOCALHOST_USER: jokerdb
    volumes:
      - /home/osmc/Docker/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
