version: "3.8"
services:
  hacker:
    image: kalilinux:aircrack
    container_name: aircrack
    network_mode: host
    environment:
      - TZ=America/Mexico_City
    volumes:
      - /tmp:/tmp
    ports:
      - 8080:80
    restart: unless-stopped
    privileged: true
