---
services:
  db:
    image: mariadb:latest
    container_name: mariadb_server
    restart: unless-stopped
    environment:
      # MYSQL_USER: $MYSQL_USER
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSW
      # MYSQL_DATABASE: $MYSQL_DATABASE
      # MYSQL_PASSWORD: $MYSQL_PASSW
      # volumes:
      #   - ./data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: mariadb_phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
