---
services:
  transmission:
    image: linuxserver/transmission:arm32v7-version-4.0.3-r2
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Mexico_City
        #- TRANSMISSION_WEB_HOME=/combustion-release/ #optional
        #- USER=username #optional
        #- PASS=password #optional
    volumes:
      - /path/to/data:/config
      - /path/to/downloads:/downloads
      - /path/to/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
