version: "2.1"
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Mexico_City
    volumes:
      - ./config:/config
    # ports:
    #   - 51820:51820/udp
    # sysctls:
    #   - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
